In [79]:
# Задача 1. Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks):
# zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110],
# ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832].
# Используя математические операции, посчитать коэффициенты линейной регрессии, приняв за X заработную плату (то есть, zp - 
# признак), а за y - значения скорингового балла (то есть, ks - целевая переменная). Произвести расчет как с использованием 
# intercept, так и без.
import numpy as np

In [80]:
# с помощью формул 
zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [81]:
n = zp.shape[0]

In [82]:
b1 = (n*np.sum(zp*ks) - zp.sum()*ks.sum()) / (n*np.sum(zp**2) - np.sum(zp)**2)
b1

2.6205388824027653

In [83]:
b0 = ks.mean() - b1*zp.mean()
b0

444.17735732435955

In [84]:
# ks = 444.18 + 2.62*zp

In [85]:
# Проверка
from sklearn.linear_model import LinearRegression

In [86]:
model = LinearRegression()

In [87]:
zp = zp.reshape(-1,1)
zp

array([[ 35],
       [ 45],
       [190],
       [200],
       [ 40],
       [ 70],
       [ 54],
       [150],
       [120],
       [110]])

In [88]:
regres = model.fit(zp,ks)
print(regres.intercept_)
print(regres.coef_)

444.1773573243596
[2.62053888]


In [106]:
# матричный метод для y = b1 * x
zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [109]:
x = zp.reshape((n,1))
x

array([[ 35],
       [ 45],
       [190],
       [200],
       [ 40],
       [ 70],
       [ 54],
       [150],
       [120],
       [110]])

In [111]:
y = ks.reshape((n,1))
y

array([[401],
       [574],
       [874],
       [919],
       [459],
       [739],
       [653],
       [902],
       [746],
       [832]])

In [114]:
B = np.dot(np.linalg.inv(np.dot(x.T, x)), x.T@y)
B

array([[5.88982042]])

In [ ]:
# b1 = 5.89
# ks = 5.89 * zp

In [100]:
# Задача 2. Посчитать коэффициент линейной регрессии при заработной плате (zp), используя градиентный спуск (без intercept).
def mse_(B1, y = ks, x = zp, n = 10):
    return np.sum((B1*x - y)**2)/n

In [101]:
zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])
alpha = 1e-6
B1 = 0.1

In [102]:
for i in range(10):
    B1 -= alpha * (2/n) * np.sum((B1*zp - ks) * zp)
    print('B1 = {}'.format(B1))

B1 = 0.25952808
B1 = 0.414660650906144
B1 = 0.5655188230595969
B1 = 0.7122203698240712
B1 = 0.8548798195302346
B1 = 0.9936085448867542
B1 = 1.1285148499277806
B1 = 1.2597040545647504
B1 = 1.387278576808517
B1 = 1.5113380127259965


In [103]:
for i in range(3000):
    B1 -= alpha * (2/n) * np.sum((B1*zp - ks) * zp)
    if i % 500 == 0:
        print('Iteration = {i}, B1 = {B1}, mse = {mse}'.format(i = i, B1 = B1, mse = mse_(B1)))

Iteration = 0, B1 = 1.6319792141937546, mse = 306275.7568040035
Iteration = 500, B1 = 5.889816771625289, mse = 56516.8584159028
Iteration = 1000, B1 = 5.8898204201295625, mse = 56516.85841571941
Iteration = 1500, B1 = 5.889820420132673, mse = 56516.85841571943
Iteration = 2000, B1 = 5.889820420132673, mse = 56516.85841571943
Iteration = 2500, B1 = 5.889820420132673, mse = 56516.85841571943


In [104]:
# B1 = 5.89
# ks = 5.89 * zp

In [105]:
# Задача 3 (Дополнительно). Произвести вычисления как в пункте 2, но с вычислением intercept. Учесть, что изменение коэффициентов
# должно производиться на каждом шаге одновременно (то есть изменение одного коэффициента не должно влиять на изменение другого
# во время одной итерации).

# Я не знаю как((